name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          TESTING: true
        run: |
          cd backend
          python -m pytest tests/ -v --tb=short

      - name: Check code formatting
        run: |
          cd backend
          pip install black
          python -m black --check app tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to Render
        run: |
          echo "🚀 Deploying to Render..."
          echo "Add Render deployment hook or API call here when ready"
          echo "Visit https://render.com to set up automatic deployments from this repo"